std_padx = 13
std_pady = 9
letter_padx = 12
extra_padx = 14


Data = {
    "1": ["1", std_padx, std_pady, 55, 15, "pinky_left"],
    "2": ["2", std_padx, std_pady, 95, 15, "ring_left"],
    "3": ["3", std_padx, std_pady, 135, 15, "middle_left"],
    "4": ["4", std_padx, std_pady, 175, 15, "index_left"],
    "5": ["5", std_padx, std_pady, 215, 15, "index_left"],
    "6": ["6", std_padx, std_pady, 255, 15, "index_right"],
    "7": ["7", std_padx, std_pady, 295, 15, "index_right"],
    "8": ["8", std_padx, std_pady, 335, 15, "middle_right"],
    "9": ["9", std_padx, std_pady, 375, 15, "ring_right"],
    "0": ["0", std_padx, std_pady, 415, 15, "pinky_right"],
    "minus": ["-", std_padx, std_pady, 455, 15, "pinky_right"],
    "equal": ["+", std_padx, std_pady, 495, 15, "pinky_right"],
    "backspace": ["          <-", std_padx, std_pady, 537, 15, "pinky_right"],
    "tab": ["TAB |<-", std_padx, std_pady, 10, 55, "pinky_left"],
    "q": ["Q", letter_padx, std_pady, 85, 55, "pinky_left"],
    "w": ["W", letter_padx, std_pady, 127, 55, "ring_left"],
    "e": ["E", letter_padx+1, std_pady, 171, 55, "middle_left"],
    "r": ["R", letter_padx, std_pady, 213, 55, "index_left"],
    "t": ["T", letter_padx, std_pady, 253, 55, "index_left"],
    "y": ["Y", letter_padx, std_pady, 293, 55, "index_right"],
    "u": ["U", letter_padx, std_pady, 333, 55, "index_right"],
    "i": ["I", extra_padx, std_pady, 373, 55, "middle_right"],
    "o": ["O", letter_padx, std_pady, 413, 55, "ring_right"],
    "p": ["P", extra_padx, std_pady, 455, 55, "pinky_right"],
    "bracketleft": ["[", letter_padx+1, std_pady, 495, 55, "pinky_right"],
    "bracketright": ["]", letter_padx+1, std_pady, 535, 55, "pinky_right"],
    "backslash": ["\\", letter_padx+1, std_pady, 575, 55, "pinky_right"],
    "caps_lock": ["Caps        ", letter_padx, std_pady, 10, 95, "pinky_left"],
    "a": ["A", letter_padx, std_pady, 95, 95, "pinky_left"],
    "s": ["S", letter_padx, std_pady, 135, 95, "ring_left"],
    "d": ["D", letter_padx, std_pady, 175, 95, "middle_left"],
    "f": ["F", letter_padx, std_pady, 215, 95, "index_left"],
    "g": ["G", letter_padx, std_pady, 255, 95, "index_left"],
    "h": ["H", letter_padx, std_pady, 295, 95, "index_right"],
    "j": ["J", extra_padx, std_pady, 335, 95, "index_right"],
    "k": ["K", letter_padx, std_pady, 375, 95, "middle_right"],
    "l": ["L", letter_padx, std_pady, 415, 95, "ring_right"],
    "semicolon": [":", extra_padx, std_pady, 455, 95, "pinky_right"],
    "quoteright": ["'", extra_padx, std_pady, 495, 95, "pinky_right"],
    "return": ["Enter\t", letter_padx, std_pady, 534, 95, "pinky_right"],
    "shift_l": ["Shift\t  ", extra_padx, std_pady, 10, 135, "pinky_left"],
    "z": ["Z", letter_padx, std_pady, 100, 135, "pinky_left"],
    "x": ["X", letter_padx, std_pady, 140, 135, "ring_left"],
    "c": ["C", letter_padx, std_pady, 180, 135, "middle_left"],
    "v": ["V", letter_padx, std_pady, 220, 135, "index_left"],
    "b": ["B", letter_padx, std_pady, 260, 135, "index_left"],
    "n": ["N", letter_padx, std_pady, 300, 135, "index_right"],
    "m": ["M", letter_padx, std_pady, 340, 135, "index_right"],
    "comma": [",", extra_padx, std_pady, 380, 135, "middle_right"],
    "period": [".", extra_padx, std_pady, 420, 135, "ring_right"],
    "slash": ["/", extra_padx, std_pady, 460, 135, "pinky_right"],
    "shift_r": ["Shift                  ", extra_padx, std_pady, 500, 135, "pinky_right"],
    "space": ["\t\t\t\t         ", extra_padx, std_pady, 160, 175, "thumbs"],
    "control_l": ["Ctrl", extra_padx, std_pady, 10, 175, "pinky_right"],
    "control_r": ["Ctrl", extra_padx, std_pady, 559, 175, "pinky_right"],
    "alt_l": ["Alt", extra_padx, std_pady, 110, 175, "pinky_right"],
    "alt_r": ["Alt", extra_padx, std_pady, 415, 175, "pinky_right"]
}
